### PR TITLE
Fix boxplot

### LINKED ISSUE #37: boxplot is highlighted strangely
``` r
library(ggplot2)
library(gghighlight)

ggplot(mpg, aes(class, hwy, colour = cyl)) +
  geom_boxplot() +
  geom_highlight(cyl > 4)
#> Warning: You set use_group_by = TRUE, but grouped calculation failed.
#> Falling back to ungrouped filter operation...
```

``` r
ggplot(mpg, aes(class, hwy, colour = cyl, group = class)) +
  geom_boxplot() +
  geom_highlight(cyl > 4)
#> Warning: You set use_group_by = TRUE, but grouped calculation failed.
#> Falling back to ungrouped filter operation...
#> Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
#> Error: Column `x` must be a 1d atomic vector or a list
```

### LINKED ISSUE #43: label_key can be call

### PR DESCRIPTION
**Pull request by yutannihilation**
- [x] respect stat aesthetics
- [x] use group ID

fixes #37, also fixes #43

### CODE REVIEW

File: R/geom_highlight.R [hunk 1]
```diff
@@ -165,32 +184,35 @@ bleach_layer <- function(layer, group_key,
...
-  if (!is.null(group_key)) {
+  if (!is.null(group_info$key)) {
     # Add group var to preserver implicit grouping to prevent the bleached
     # data to facetted, rename the group column to the very improbable name.
     # e.g. geom_line(aes(colour = c)); if colour aes is removed, line will be drawn unintentionally.
     # But, is group key always needed...? (e.g. points)
-    layer$data <- dplyr::rename(layer$data, !!VERY_SECRET_COLUMN_NAME := !!group_key)
+    secret_colname <- rlang::expr_text(VERY_SECRET_COLUMN_NAME)
+    names(group_info$key) <- paste0(secret_colname, seq_along(group_info$key))
+    layer$data <- dplyr::rename(layer$data, !!!group_info$key)
```
Comment (yutannihilation) [inline R/geom_highlight.R]: It's not always that group keys can be renamed; it may be mapped from the other aes.
Usually, this won't be the problem because it is typically `colour` or `fill`, which are overwritten by grey.
But, if `x` is used for grouping, `x` is necessary. Other aes like `shape` might be also the case.

**Comment by yutannihilation** [comment]
``` r
library(ggplot2)
library(gghighlight)

# OK
ggplot(mpg, aes(class, hwy, colour = cyl)) +
  geom_boxplot() +
  geom_highlight(max(hwy) > 40)
```



``` r

# Why...?
ggplot(mpg, aes(class, hwy, colour = factor(cyl))) +
  geom_boxplot() +
  geom_highlight(max(hwy) > 40)
```



Created on 2018-05-31 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by yutannihilation** [comment]
Ah, this is a limitation; boxplot's variable widths determines according to the relative size of the group, so, if the data is filtered, the widths cannot be the same.
